import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@ksurdhar/react-nice-dates/build/style.css'
import './globals.css'

const inter = Inter({
  style: 'normal',
  weight: ['400', '600'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-soft-black`}>{children}</body>
    </html>
  )
}
